query MatchesQuery($guild_id: Int!, $take: Int!) {
  guild(id: $guild_id) {
    id
    name
    logo
    matches(take: $take) {
      id
      lobbyType
      gameMode
      durationSeconds
      endDateTime
      players(steamAccountId: null) {
        isVictory
        isRadiant
        imp
        kills
        deaths
        assists
        hero {
          id
          displayName
        }
        steamAccount {
          name
        }
      }
    }
  }
}
